### ISSUE TITLE
Unable to install Javascript pacakge

### ISSUE THREAD

**Issue by JenspederM** [facebook/yoga#1230] opened 2023-02-20 16:13 UTC
# Report

- [x ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
```
yarn add yoga-layout
```

# Expected Behavior
Package successfully installed

# Actual Behavior

## With Pyenv set to Python 3.8.10

```

error /.../node_modules/yoga-layout: Command failed.
Exit code: 1
Command: npm run build:node
Arguments: 
Directory: /.../node_modules/yoga-layout
Output:
> yoga-layout@1.9.3 build:node
> npm run copy-sources && autogypi && node-gyp configure build


> yoga-layout@1.9.3 copy-sources
> ! npm -s run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)

gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@16.19.0 | darwin | arm64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /.../.pyenv/shims/python2 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack pyenv: python2: command not found
gyp ERR! stack 
gyp ERR! stack The `python2' command exists in these Python versions:
gyp ERR! stack   2.7.18
gyp ERR! stack 
gyp ERR! stack Note: See 'pyenv help global' for tips on allowing both
gyp ERR! stack       python2 and python3 to be found.
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:402:12)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
gyp ERR! System Darwin 22.2.0
gyp ERR! command "/.../.config/nvm/versions/node/v16.19.0/bin/node" "/.../node_modules/yoga-layout/node_modules/.bin/node-gyp" "configure" "build"
gyp ERR! cwd /.../node_modules/yoga-layout
gyp ERR! node -v v16.19.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

## With Pyenv set to Python 2.7.18

```
error /.../node_modules/yoga-layout: Command failed.
Exit code: 1
Command: npm run build:node
Arguments: 
Directory: /.../node_modules/yoga-layout
Output:
> yoga-layout@1.9.3 build:node
> npm run copy-sources && autogypi && node-gyp configure build


> yoga-layout@1.9.3 copy-sources
> ! npm -s run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)

gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@16.19.0 | darwin | arm64
(node:77411) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /.../.pyenv/shims/python2
gyp info spawn args [
gyp info spawn args   '/.../node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/...node_modules/yoga-layout/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/.../node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/.../.node-gyp/16.19.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/....node-gyp/16.19.0',
gyp info spawn args   '-Dnode_gyp_dir=/.../node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/.../.node-gyp/16.19.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/.../node_modules/yoga-layout',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  COPY Release/obj.target/nbind/geni/symbols.txt
  CXX(target) Release/obj.target/nbind/sources/yoga/Utils.o
  CXX(target) Release/obj.target/nbind/sources/yoga/YGEnums.o
  CXX(target) Release/obj.target/nbind/sources/yoga/YGNode.o
  CXX(target) Release/obj.target/nbind/sources/yoga/YGNodePrint.o
  CXX(target) Release/obj.target/nbind/sources/yoga/Yoga.o
../sources/yoga/Yoga.cpp:3111:55: warning: suspicious concatenation of string literals in an array initialization; did you mean to separate the elements with a comma? [-Wstring-concatenation]
                                                      "MOST"};
                                                      ^
../sources/yoga/Yoga.cpp:3110:55: note: place parentheses around the string literal to silence warning
                                                      "LAY_AT_"
                                                      ^
1 warning generated.
  CXX(target) Release/obj.target/nbind/sources/Config.o
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:71:
../../nbind/include/nbind/v8/BindWrapper.h:216:63: error: too few arguments to function call, single argument 'context' was not specified
                auto flags = static_cast<TypeFlags>(nanArgs[1]->Uint32Value());
                                                    ~~~~~~~~~~~~~~~~~~~~~~~ ^
/.../.node-gyp/16.19.0/include/node/v8.h:3104:41: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                        ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:71:
../../nbind/include/nbind/v8/BindWrapper.h:216:16: error: cannot convert 'Maybe<uint32_t>' (aka 'Maybe<unsigned int>') to 'nbind::TypeFlags' without a conversion operator
                auto flags = static_cast<TypeFlags>(nanArgs[1]->Uint32Value());
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindWrapper.h:217:38: error: expected '(' for function-style cast or type construction
                void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
                                       ~~~~~~~~~~~~^
../../nbind/include/nbind/v8/BindWrapper.h:217:19: error: no member named 'Handle' in namespace 'v8'
                void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
                            ~~~~^
../../nbind/include/nbind/v8/BindWrapper.h:217:41: error: no member named 'Cast' in the global namespace
                void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
                                                    ~~^
../../nbind/include/nbind/v8/BindWrapper.h:217:19: error: 'handle_' is a private member of 'node::ObjectWrap'
                void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
                                ^
/.../.node-gyp/16.19.0/include/node/node_object_wrap.h:127:30: note: declared private here
  v8::Persistent<v8::Object> handle_;
                             ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:52:18: error: too few arguments to function call, single argument 'context' was not specified
                        arg->ToObject(),
                        ~~~~~~~~~~~~~ ^
/.../.node-gyp/16.19.0/include/node/v8.h:3060:44: note: 'ToObject' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:96:18: error: too few arguments to function call, single argument 'context' was not specified
                        arg->ToObject(),
                        ~~~~~~~~~~~~~ ^
/.../.node-gyp/16.19.0/include/node/v8.h:3060:44: note: 'ToObject' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:187:1: error: too few arguments to function call, single argument 'isolate' was not specified
DEFINE_NATIVE_BINDING_TYPE(bool, IsBoolean, BooleanValue, v8::Boolean);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/.../.node-gyp/16.19.0/include/node/v8.h:3096:8: note: 'BooleanValue' declared here
  bool BooleanValue(Isolate* isolate) const;
       ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:189:1: error: too few arguments to function call, single argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(double, IsNumber, NumberValue, v8::Number);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/.../.node-gyp/16.19.0/include/node/v8.h:3099:39: note: 'NumberValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                      ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:189:1: error: cannot convert 'Maybe<double>' to 'nbind::BindingType<double>::Type' (aka 'double') without a conversion operator
DEFINE_NATIVE_BINDING_TYPE(double, IsNumber, NumberValue, v8::Number);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:10: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:190:1: error: too few arguments to function call, single argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(float, IsNumber, NumberValue, v8::Number);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/.../.node-gyp/16.19.0/include/node/v8.h:3099:39: note: 'NumberValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                      ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:190:1: error: cannot convert 'Maybe<double>' to 'nbind::BindingType<float>::Type' (aka 'float') without a conversion operator
DEFINE_NATIVE_BINDING_TYPE(float, IsNumber, NumberValue, v8::Number);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:10: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:192:1: error: too few arguments to function call, single argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(unsigned int, IsNumber, Uint32Value, v8::Uint32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/.../.node-gyp/16.19.0/include/node/v8.h:3104:41: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                        ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:192:1: error: cannot convert 'Maybe<uint32_t>' (aka 'Maybe<unsigned int>') to 'nbind::BindingType<unsigned int>::Type' (aka 'unsigned int') without a conversion operator
DEFINE_NATIVE_BINDING_TYPE(unsigned int, IsNumber, Uint32Value, v8::Uint32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:10: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:193:1: error: too few arguments to function call, single argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(unsigned short, IsNumber, Uint32Value, v8::Uint32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/.../.node-gyp/16.19.0/include/node/v8.h:3104:41: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                        ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:193:1: error: cannot convert 'Maybe<uint32_t>' (aka 'Maybe<unsigned int>') to 'nbind::BindingType<unsigned short>::Type' (aka 'unsigned short') without a conversion operator
DEFINE_NATIVE_BINDING_TYPE(unsigned short, IsNumber, Uint32Value, v8::Uint32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:10: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:194:1: error: too few arguments to function call, single argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(unsigned char, IsNumber, Uint32Value, v8::Uint32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/.../.node-gyp/16.19.0/include/node/v8.h:3104:41: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                        ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:194:1: error: cannot convert 'Maybe<uint32_t>' (aka 'Maybe<unsigned int>') to 'nbind::BindingType<unsigned char>::Type' (aka 'unsigned char') without a conversion operator
DEFINE_NATIVE_BINDING_TYPE(unsigned char, IsNumber, Uint32Value, v8::Uint32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:10: note: expanded from macro 'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/nbind/sources/Config.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/.../node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Darwin 22.2.0
gyp ERR! command "/.../.config/nvm/versions/node/v16.19.0/bin/node" "/.../node_modules/yoga-layout/node_modules/.bin/node-gyp" "configure" "build"
gyp ERR! cwd /.../node_modules/yoga-layout
gyp ERR! node -v v16.19.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

# Link to Code
***If you have some code that maintainers can clone/test for themselves, bugs can be resolved much faster. Please paste a link here.***

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

**Comment by NickGerleman** [comment] 2023-02-21 03:13
Dupe of #979

We have fixed it locally, and added a new async-loaded API to allow WASM in browser, but haven't yet published the new package yet. Hoping this should happen soon.

**Closed by NickGerleman** 2023-02-21 03:13 UTC

**Comment by JenspederM** [comment] 2023-03-11 22:30
Do you have an ETA for the new release? 

Also, if I can do anything to help speed to along, please let me know.
