### ISSUE TITLE
ios crash on version 1.14.0

### ISSUE THREAD

**Issue by trololo15** [facebook/yoga#911] opened 2019-06-30 09:11 UTC
i installed both Yoga and YogaKit of version 1.14.0(newest on cocoapods)  in a completely new project.
and here is the code: 

[self.view configureLayoutWithBlock:^(YGLayout * _Nonnull layout) {
        layout.isEnabled = YES;
        layout.paddingTop = YGPointValue(50);
        layout.alignItems = YGAlignCenter;
    }];
    
    UIView *v = [[UIView alloc] init];
    v.backgroundColor = [UIColor redColor];
    [self.view addSubview:v];
    [v configureLayoutWithBlock:^(YGLayout * _Nonnull layout) {
        layout.isEnabled = YES;
        layout.width = YGPointValue(50);
        layout.height = YGPointValue(50);
    }];
    
    [self.view.yoga applyLayoutPreservingOrigin:YES];

every time i run it, it just crash with an exception: 
Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]'

**Comment by cntrump** [comment] 2019-07-04 11:38
I fixed in my fork [cntrump/yoga](https://github.com/cntrump/yoga)

**Comment by tranty9597** [comment] 2019-07-26 06:34
> I fixed in my fork [cntrump/yoga](https://github.com/cntrump/yoga)

could u explain why this exception excecute, and how do u fix it

**Comment by cntrump** [comment] 2019-07-26 09:27
> > I fixed in my fork [cntrump/yoga](https://github.com/cntrump/yoga)
> 
> could u explain why this exception excecute, and how do u fix it

Sure, It is very simple

In function `static void YGApplyLayoutToViewHierarchy(UIView *view, BOOL preserveOrigin)`
`width` or `height` could be negative
```objc
.size = {
	      .width = YGRoundPixelValue(bottomRight.x) - YGRoundPixelValue(topLeft.x),
	      .height = YGRoundPixelValue(bottomRight.y) - YGRoundPixelValue(topLeft.y),
	    },
```
After fixing
```objc
	      .width = MAX(0, YGRoundPixelValue(bottomRight.x) - YGRoundPixelValue(topLeft.x)),
	      .height = MAX(0, YGRoundPixelValue(bottomRight.y) - YGRoundPixelValue(topLeft.y)),
```

**Comment by cntrump** [comment] 2019-07-26 09:52
and, this is my PR https://github.com/facebook/yoga/pull/913

**Comment by trololo15** [comment] 2019-07-26 09:56
> > > I fixed in my fork [cntrump/yoga](https://github.com/cntrump/yoga)
> > 
> > 
> > could u explain why this exception excecute, and how do u fix it
> 
> Sure, It is very simple
> 
> In function `static void YGApplyLayoutToViewHierarchy(UIView *view, BOOL preserveOrigin)`
> `width` or `height` could be negative
> 
> ```objc
> .size = {
> 	      .width = YGRoundPixelValue(bottomRight.x) - YGRoundPixelValue(topLeft.x),
> 	      .height = YGRoundPixelValue(bottomRight.y) - YGRoundPixelValue(topLeft.y),
> 	    },
> ```
> 
> After fixing
> 
> ```objc
> 	      .width = MAX(0, YGRoundPixelValue(bottomRight.x) - YGRoundPixelValue(topLeft.x)),
> 	      .height = MAX(0, YGRoundPixelValue(bottomRight.y) - YGRoundPixelValue(topLeft.y)),
> ```

Great! It worked. thanks my friend;

**Comment by trololo15** [comment] 2019-07-26 10:03
> and, this is my PR #913

There is another issue, if i set a view yogaLayout like this:

**Comment by trololo15** [comment] 2019-07-26 10:16
> and, this is my PR #913

there is another issue, if i set a view yogaLayout height < 1, code like this:
[view configureLayoutWithBlock:^(YGLayout * _Nonnull layout) {
        layout.height = YGPointValue(0.5);
 }];

eventually the view height will be rendered as 0.67,  and occasionally be 1.

and this situation only happens on iPhone 8 plus , x , xs max; iPhone 8 7 6  are fine.

so i think this may relevant with screen scale

**Comment by cntrump** [comment] 2019-07-26 10:28
> > and, this is my PR #913
> 
> there is another issue, if i set a view yogaLayout height < 1, code like this:
> [view configureLayoutWithBlock:^(YGLayout * _Nonnull layout) {
> layout.height = YGPointValue(0.5);
> }];
> 
> eventually the view height will be rendered as 0.67, and occasionally be 1.
> 
> and this situation only happens on iPhone 8 plus , x , xs max; iPhone 8 7 6 are fine.
> 
> so i think this may relevant with screen scale

It is not a bug, it is aligned to the pixel:
```c
ceil(0.5 * scale) / scale
```

on iPhone 8p, scale is 3, so the reuslt is `0.6666666`

**Comment by trololo15** [comment] 2019-07-26 10:35
> > > and, this is my PR #913
> > 
> > 
> > there is another issue, if i set a view yogaLayout height < 1, code like this:
> > [view configureLayoutWithBlock:^(YGLayout * _Nonnull layout) {
> > layout.height = YGPointValue(0.5);
> > }];
> > eventually the view height will be rendered as 0.67, and occasionally be 1.
> > and this situation only happens on iPhone 8 plus , x , xs max; iPhone 8 7 6 are fine.
> > so i think this may relevant with screen scale
> 
> It is not a bug, it is aligned to the pixel:
> 
> ```c
> ceil(0.5 * scale) / scale
> ```
> 
> on iPhone 8p, scale is 3, so the reuslt is `0.6666666`

cool! It is so glad to discuss this with you. coz nearly no one use yogakit around me :)

**Comment by cntrump** [comment] 2019-07-26 10:43
> > > > and, this is my PR #913
> > > 
> > > 
> > > there is another issue, if i set a view yogaLayout height < 1, code like this:
> > > [view configureLayoutWithBlock:^(YGLayout * _Nonnull layout) {
> > > layout.height = YGPointValue(0.5);
> > > }];
> > > eventually the view height will be rendered as 0.67, and occasionally be 1.
> > > and this situation only happens on iPhone 8 plus , x , xs max; iPhone 8 7 6 are fine.
> > > so i think this may relevant with screen scale
> > 
> > 
> > It is not a bug, it is aligned to the pixel:
> > ```c
> > ceil(0.5 * scale) / scale
> > ```
> > 
> > 
> > on iPhone 8p, scale is 3, so the reuslt is `0.6666666`
> 
> cool! It is so glad to discuss this with you. coz nearly no one use yogakit around me :)

😁🤝

**Comment by nferruzzi** [comment] 2019-07-26 10:59
if you feel alone just try https://creolabs.com/ it exports swift yoga code :)

**Closed** 2019-07-30 08:17 UTC
