### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by ultimate-deej** [facebook/yoga#1151] opened 2022-06-07 12:33 UTC
There are hundreds of open issues and PRs, many of which have been around for months and even years now.

Pods are outdated. "YogaKit" on CocoaPods is version 1.18.1 which is missing in this repo, while version v1.19.0 was released more than a year ago and is still unavailable. Ok the release notes tell "Release for Maven Central.", which suggests it's irrelevant for iOS, but what is version 1.18.1 then? And the "yoga" pod is 1.14.0, clearly far behind the main pod.

Speaking of iOS. There are also a few fundamental problems, like not working properly with iOS transforms, or that in order for a child to be laid out by a yoga-enabled parent, you need to enable all the Yoga machinery for the child as well. That makes it particularly difficult to use with, say, UIScrollView.

----

My question is, is this project considered for further development, and should I bother opening new issues, or creating new PRs?

**Comment by furkanarabaci** [comment] 2022-06-08 08:29
AFAIK `react-native` also uses yoga as their "backend". Supposedly the repo shouldn't be dead, but who knows...

**Comment by woehrl01** [comment] 2022-06-19 14:50
The last kind of official statement I know of are [the following tweets](https://twitter.com/reactnative/status/1428452897121964035?t=_rtPPnEXxsZHJsehN1uF3A&s=19) by @TheSavior . So sad it is, I guess the repo will not get the attention it deserves in the near future, that's why I stopped submitting PRs years ago.

**Comment by cntrump** [comment] 2022-06-24 05:02
My fork still alive: https://github.com/cntrump/yoga

I added some little improves:
- `float` -> `double`
- allow negative padding
- fix some crash issues in YogaKit

**Comment by KurtGokhan** [comment] 2022-06-26 13:49
No offense anyone, but I think this repo is maintained pretty badly for a library that is used in some of the most important apps around the world.

Also I wonder why they added `static` position and shifted all other positions in 1.19.0, basically breaking backward compatibility with previous versions.

**Comment by NickGerleman** [comment] 2022-09-30 21:43
I'm going to be spending some time trying to get this repo into a cleaner state. If there are any issues or PRs folks feel passionate about, please let me know in this thread.

**Comment by AndrewAPrice** [comment] 2022-10-25 20:31
Nick, I'd really like to see CSS grid support. The lack of grid makes it difficult to build tables. https://github.com/facebook/yoga/issues/867

**Comment by brianguertin** [comment] 2022-11-10 03:28
@AndrewAPrice Yoga is a flexbox implementation, CSS grid is entirely separate concept, wouldn't it be basically a brand new library?

**Comment by AndrewAPrice** [comment] 2022-11-10 13:59
@brianguertin you could argue that. Since on the web you can embed grids and flexboxes within each other and many of the attributes are shared in name and behavior, it would be nice if there were a layouting engine that could handle them both in a generic way.

**Comment by QOAL** [comment] 2022-12-02 16:19
One thing I would like to see added is support for overflow alignment keywords, `safe` / `unsafe`.
https://w3c.github.io/csswg-drafts/css-align/#overflow-values

**Comment by brianguertin** [comment] 2022-12-03 20:44
@QOAL I was able to shim `safe` support in my use case, but it won't work for everyone:

Whenever I'm assigning "justify-content" to a node, I first check the sum of the main axis size of all the children.

If the sum is greater than the flexbox's size, I replace justify-content with "start". Otherwise, I apply the configured justify-content as intended. This is what the "safe" keyword does.

This only works because in my use case because I evaluate each node of my UI tree independently; so I always know the actual size of the flexbox and the desired size of the children.

But it would be neater if Yoga supported it :)

**Comment by brianguertin** [comment] 2022-12-14 13:13
For my use case I need Yoga in a Kotlin multiplatform codebase. This means ideally using it in `commonMain` sources, which are shared across platforms (Android, iOS, Web, etc.).

I ran into some challenges trying to use Yoga as-is:

1) I had to individually wrap JS, Android, and iOS binaries with a common Kotlin API, so I could call it from common source set

2) I could not figure out how to get it working for running unit tests on my laptop, as there is no JVM build for OSX available.


So.... I ended up converting Yoga entirely to pure Kotlin (no C++ or JNI remaining). Based on somebody else's previous conversion to pure Java.

Amazingly, all the unit tests still pass, and I now have a simple Kotlin library that can be dropped into any Kotlin project, in case anyone else needs it, I published here: https://github.com/Joingo/yoga-kotlin

**Comment by XantreGodlike** [comment] 2023-02-21 10:09
What with the project now?

**Comment by woehrl01** [comment] 2023-02-21 10:13
@XantreGodlike please have a look in the latest history of the repo. Since @NickGerleman picked things up, this repo is alive again.

**Comment by NickGerleman** [comment] 2023-07-01 00:40
We just put out a new proper release with https://github.com/facebook/yoga/releases/tag/v2.0.0-beta.1.

I think that's the last thing I wanted to do before closing this issue out 🙂.

**Closed by NickGerleman** 2023-07-01 00:40 UTC
Labels: Discussion
