### ISSUE TITLE
Non-Android Java build

### ISSUE THREAD

**Issue by nornagon** [facebook/yoga#725] opened 2018-03-07 19:15 UTC
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
I'd like to use Yoga in a JVM project not targeted at Android. The [jcenter](https://bintray.com/facebook/maven/com.facebook.yoga%3Ayoga/1.7.0#files/com%2Ffacebook%2Fyoga%2Fyoga%2F1.7.0) repository only has AARs, and there are no instructions about how to build JARs for non-Android platforms. [lwjgl](https://javadoc.lwjgl.org/index.html?org/lwjgl/util/yoga/Yoga.html) has bindings, but they are very lightly typed and require manual memory management.

# Expected Behavior
It doesn't look like there's very much in the way of building a JAR file for non-Android JVMs, it'd be awesome to push it over the line!

**Comment by Spasi** [comment] 2018-03-07 20:16
> lwjgl has bindings, but they are very lightly typed and require manual memory management.

Please note that it's trivial to create your own OO wrapper on top of the lwjgl bindings. See [this example](https://github.com/LWJGL/lwjgl3/blob/00e1f52cf95c16b0cea34c83372145532b4745ba/modules/lwjgl/yoga/src/test/java/org/lwjgl/util/yoga/YogaNode.java), which passes the [same unit tests](https://github.com/LWJGL/lwjgl3/tree/00e1f52cf95c16b0cea34c83372145532b4745ba/modules/lwjgl/yoga/src/test/java/org/lwjgl/util/yoga) from the official Yoga repository.

Creating wrappers is outside the scope of LWJGL, but I would also argue against it in general:

- Manual memory management may be a burden, but using a finalizer to free the native handles is not ideal either. See [Deprecate Object.finalize](https://bugs.openjdk.java.net/browse/JDK-8165641).
- It's very likely that the application that uses Yoga already has some kind of DOM-style node hierarchy structure. In that case, the wrapper instances is just overhead.

**Comment by nornagon** [comment] 2018-03-08 00:44
I didn't see that YogaNode example in the tests, that's awesome! Looks like it'd be worth copy/pasting into my project, 🙇

I see where you're coming from with wrapper instances being overhead when you've already got some DOM structure. For my particular situation, developer brain overhead is much more expensive than CPU/memory overhead, since I'm substantially underusing the CPU, and I'd like to make a different trade-off. I'd like to be able to install that trade-off from Maven Central or JCenter, rather than cobbling it together myself :)

FWIW, the [javacpp](https://github.com/bytedeco/javacpp) project [uses PhantomReference](https://github.com/bytedeco/javacpp/blob/fa16a255c2d87974c1c7cd672aceff9efdd04eae/src/main/java/org/bytedeco/javacpp/Pointer.java) and friends to bridge Java's memory management to C++, rather than using finalizers.

**Comment by NickGerleman** [comment] 2022-10-04 17:52
Duplicate of #929

**Closed by NickGerleman** 2022-10-04 17:52 UTC
