### ISSUE TITLE
[Playground] flexDirection is missing in the generated code for ReactNative

### ISSUE THREAD

**Issue by rhazegh** [facebook/yoga#732] opened 2018-03-15 00:21 UTC
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
- Go to https://goo.gl/2VvJQy
- Get code > React Native

# Expected Behavior
Elements that have `Flex Direction: row` must have `flexDirection: 'row'` in the generated code for react native.

# Actual Behavior
`flexDirection: 'row'` is missing for all elements that have this property set (e.g. element 3)

**Comment by galtenberg** [comment] 2019-03-17 16:04
Confirmed this is an issue. Generated code does not match Playground when used in real projects.

**Comment by NickGerleman** [comment] 2022-10-04 17:46
Duplicate of #807

**Closed by NickGerleman** 2022-10-04 17:46 UTC
