### ISSUE TITLE
Support JS environments without code generation

### ISSUE THREAD

**Issue by benjavicente** [facebook/yoga#1772] opened 2024-12-17 23:42 UTC
# Report

- [X] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

Probably is related to https://github.com/facebook/yoga/issues/1507

# Problem

The `yoga-layout` JavaScript library isn't compatible with environments that disallow code generation (eval), like Cloudflare's workerd ([example related issue](https://github.com/cloudflare/next-on-pages/issues/704)). Because of that, a library that patched how the wasm was loaded took off: [yoga-wasm-web](https://www.npmjs.com/package/yoga-wasm-web) (used on [satory](https://github.com/vercel/satori)). This split isn't great for libraries that use yoga and would like to target all modern JS environments, especially since yoga-wasm-web [is stuck in yoga 2-beta](https://github.com/shuding/yoga-wasm-web/commits/main/). 

# Proposed solution

Support multiple ways to load wasm, like with a new entry point similar to [yoga-wasm-web](https://github.com/shuding/yoga-wasm-web/blob/main/index.js). But, since some libraries were built without the consideration that this option could be added, it might be better to provide a mechanism to globally configure how wasm is loaded before the initialization of libraries that use yoga:

```ts
import { setWASMLoader } from 'yoga-layout/load';

setWASMLoader((...) => WebAssembly.instantiate(...))

import { ... } from "@react-pdf/renderer" // or any other lib
```

**Comment by NickGerleman** [comment] 2024-12-24 13:08
Dupe of #1767

**Closed by NickGerleman** 2024-12-24 13:08 UTC
