### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by xiaozhuai** [facebook/yoga#1226] opened 2023-02-15 05:33 UTC
It has been year since last release. And there are many important fixes and improvement. 
Could you please release a new version?

**Comment by NickGerleman** [comment] 2023-02-15 22:37
Duplicate of #1223. There is another issue for NPM specifically as well, but TLDR: It's being worked on, but the infra to make sure it's all working needs to get fixed before we make a new release.

**Closed by NickGerleman** 2023-02-15 22:37 UTC
