### ISSUE TITLE
Using outdated version of SoLoader and causing App Crashing issues

### ISSUE THREAD

**Issue by seventhmoon** [facebook/yoga#1152] opened 2022-07-06 11:25 UTC
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
SoLoader recently fixed a few app crashing issues in `0.10.4`. However, Yoga is still using a very old version of it.

https://github.com/facebook/yoga/blob/578d197dd6652225b46af090c0b46471dc887361/lib/fb/build.gradle

# Expected Behavior
The latest version (0.10.4) is used. 

# Actual Behavior
0.10.1 is used.

# Link to Code
https://github.com/facebook/yoga/blob/578d197dd6652225b46af090c0b46471dc887361/lib/fb/build.gradle

**Comment by simpleton** [comment] 2022-07-23 00:47
thanks for reaching out. Updated in https://github.com/facebook/yoga/commit/c5a8f447b123a6d3055fca34175b086abb379a53

**Comment by NickGerleman** [comment] 2022-10-04 14:39
It looks like this issue was resolved, so I am closing it, but please reopen if the issue is still present on the latest commit. We should be releasing a more up to date Yoga Maven package soon.

**Closed by NickGerleman** 2022-10-04 14:39 UTC
