### ISSUE TITLE
Build error - use of bitwise '|' with boolean operands 

### ISSUE THREAD

**Issue by gabrielyoto** [facebook/yoga#1224] opened 2023-02-07 15:04 UTC
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues?q=bitwise) and this is not a duplicate

# Issues and Steps to Reproduce
Try to build the app
![image](https://user-images.githubusercontent.com/51537042/217344195-9948c9b4-92c3-47b4-8c8f-47dbee93168b.png)

# Environment
expo: 44.0.6
react-native: 0.68.5

Toolchain: Swift 5.7 2022-09-12

# Expected Behavior
Build without error

# Actual Behavior
Build failed with error - use of bitwise '|' with boolean operands

## Log
```
/<my-project>/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp:2232:9: error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
        node->getLayout().hadOverflow() |
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Please contact me for any questions.

Thank you very much.

**Comment by gabrielyoto** [comment] 2023-02-07 18:45
Update: This problem occurs running in a device with iOS 13.7. In newer versions it doesn't happen

**Comment by NickGerleman** [comment] 2023-02-08 04:05
Looks like this was fixed in RN 0.69+ with https://github.com/facebook/react-native/commit/52d8a797e7a6be3fa472f323ceca4814a28ef596.

@cortinico @cipolleschi would know better but my guess is you should be using an older version of XCode for an RN version at that age.

**Closed by NickGerleman** 2023-02-08 04:05 UTC

**Comment by LonelyCpp** [comment] 2023-03-24 11:24
I'm getting this error on xcode 14 on react native `v0.66.5`. Is there no other workaround other than upgrading react native?

**Comment by cipolleschi** [comment] 2023-03-27 10:29
Hi @LonelyCpp, unfortunately, we are not supporting React Native 0.66 anymore. Our suggestion is to update to the latest version.

**Comment by kyrieLiu3** [comment] 2023-04-03 06:41
What's your Xcode version?

**Comment by LonelyCpp** [comment] 2023-04-03 06:44
Xcode 14.3.x, on macOS 13.2 (Ventura) | M1 Medium

**Comment by kyrieLiu3** [comment] 2023-04-03 06:52
> Xcode 14.3.x, on macOS 13.2 (Ventura) | M1 Medium

@LonelyCpp  This morning the Xcode updated itself when opened it, now it's Version 14.3 (14E222b). I've got this error without any modification from last week. I fixed the corresponding error line but other errors occur in other third-party packages, so I doubt this might be caused by the Xcode update.

**Comment by YDisa** [comment] 2023-04-12 02:01
I am on the same issue.

After the xcode update,
My client's old app doesn't build
(Builded before update)

---
xcode : Version 14.3 (14E222b)
react-native : 0.66.2

**Comment by Platycodon** [comment] 2023-04-12 05:52
same issue on Xcode 14.3
